name: zen_launcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  android_intent_plus: ^6.0.0
  battery_optimization_helper: ^0.2.0
  do_not_disturb: ^1.0.3
  flutter:
    sdk: flutter
  flutter_notification_listener_plus: ^1.1.0
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
